export const asIsTerms = Object.freeze([
  'Logto OSS',
  'Logto Cloud',
  'Management API',
  'Experience API',
  'Account API',
  'OpenID Connect',
  'OAuth 2.0',
  'JSON Web Token',
  'JWT',
  'SAML',
  'SSO',
  'API',
  'CLI',
  'SDK',
  'IdP',
  'MFA',
  'Webhook',
]);

/**
 * Terms that should have fixed translations. The first level key is the locale, the second level key is the term, and the value is the translation.
 */
export const terms = Object.freeze({
  'zh-CN': {
    Authentication: '认证',
    Authorization: '授权',
    'Opaque Token': '不透明令牌',
    'Opaque Tokens': '不透明令牌',
    'Access Token': '访问令牌',
    'Access Tokens': '访问令牌',
    'Refresh Token': '刷新令牌',
    'Refresh Tokens': '刷新令牌',
    'ID Token': 'ID 令牌',
    'ID Tokens': 'ID 令牌',
    Issuer: '发行者 (Issuer)',
    Issuers: '发行者 (Issuers)',
    Role: '角色 (Role)',
    Roles: '角色 (Roles)',
    Audience: '受众 (Audience)',
    Audiences: '受众 (Audiences)',
    Subject: '主体 (Subject)',
    Subjects: '主体 (Subjects)',
    Scope: '权限 (Scope)',
    Scopes: '权限 (Scopes)',
    Permission: '权限',
    Permissions: '权限',
    Claim: '声明 (Claim)',
    Claims: '声明 (Claims)',
    Organization: '组织',
    Organizations: '组织',
    Connector: '连接器',
    Connectors: '连接器',
    'Consent Screen': '用户授权页面',
    'Machine-to-Machine': '机器对机器',
    Experience: '体验',
    'API Resource': 'API 资源',
    'API Resources': 'API 资源',
    'Role-Based Access Control': '基于角色的访问控制 (RBAC)',
    'User Impersonation': '用户模拟',
    'Identity Provider': '身份提供商 (IdP)',
    'Single Sign-On': '单点登录 (SSO)',
    'Enterprise SSO': '企业单点登录 (SSO)',
    'Multi-Factor Authentication': '多因素认证 (MFA)',
  },
});
