export const asIsTerms = Object.freeze([
  'Logto OSS',
  'Logto Cloud',
  'Management API',
  'Experience API',
  'Account API',
  'OpenID Connect',
  'OAuth 2.0',
  'JSON Web Token',
  'RBAC',
  'ABAC',
  'JWT',
  'SAML',
  'SSO',
  'API',
  'CLI',
  'SDK',
  'IdP',
  'MFA',
  'Webhook',
]);

/**
 * Terms that should have fixed translations. The first level key is the locale, the second level key is the term, and the value is the translation.
 */
export const terms = Object.freeze({
  'zh-CN': {
    Authentication: '认证',
    Authorization: '授权',
    'Opaque token': '不透明令牌',
    'Opaque tokens': '不透明令牌',
    'Access token': '访问令牌',
    'Access tokens': '访问令牌',
    'Refresh token': '刷新令牌',
    'Refresh tokens': '刷新令牌',
    'Organization token': '组织令牌',
    'Organization tokens': '组织令牌',
    'ID token': 'ID 令牌',
    'ID tokens': 'ID 令牌',
    Issuer: '发行者',
    Issuers: '发行者',
    Role: '角色',
    Roles: '角色',
    Audience: '受众',
    Audiences: '受众',
    Subject: '主体',
    Subjects: '主体',
    Scope: '权限',
    Scopes: '权限',
    Permission: '权限',
    Permissions: '权限',
    Claim: '声明',
    Claims: '声明',
    Organization: '组织',
    Organizations: '组织',
    Connector: '连接器',
    Connectors: '连接器',
    'Resource indicator': '资源指示器',
    'Resource indicators': '资源指示器',
    'Consent screen': '用户授权页面',
    'Machine-to-machine': '机器对机器',
    Experience: '体验',
    'API resource': 'API 资源',
    'API resources': 'API 资源',
    'Role-based access control': '基于角色的访问控制 (RBAC)',
    'User impersonation': '用户模拟',
    'Identity provider': '身份提供商 (IdP)',
    'Single sign-on': '单点登录 (SSO)',
    'Enterprise SSO': '企业单点登录 (SSO)',
    'Multi-factor authentication': '多因素认证 (MFA)',
    'Authentication request': '认证请求',
    'Authorization request': '授权请求',
    'Token request': '令牌请求',
    'Authorization token': '授权令牌',
  },
});
