/* eslint-disable max-lines */
export const asIsTerms = Object.freeze([
  'Logto',
  'Logto OSS',
  'Logto Cloud',
  'Management API',
  'Experience API',
  'Account API',
  'OpenID Connect',
  'OAuth 2.0',
  'JSON Web Token',
  'RBAC',
  'ABAC',
  'JWT',
  'SAML',
  'SSO',
  'API',
  'CLI',
  'SDK',
  'IdP',
  'MFA',
  'Webhook',
]);

/**
 * Terms that should have fixed translations. The first level key is the locale, the second level key is the term, and the value is the translation.
 */
export const terms = Object.freeze({
  'zh-CN': {
    Authentication: '认证',
    Authorization: '授权',
    'Opaque token': '不透明令牌',
    'Opaque tokens': '不透明令牌',
    'Access token': '访问令牌',
    'Access tokens': '访问令牌',
    'Refresh token': '刷新令牌',
    'Refresh tokens': '刷新令牌',
    'Organization token': '组织令牌',
    'Organization tokens': '组织令牌',
    'ID token': 'ID 令牌',
    'ID tokens': 'ID 令牌',
    Issuer: '发行者',
    Issuers: '发行者',
    Role: '角色',
    Roles: '角色',
    Audience: '受众',
    Audiences: '受众',
    Subject: '主体',
    Subjects: '主体',
    Scope: '权限',
    Scopes: '权限',
    Permission: '权限',
    Permissions: '权限',
    Claim: '声明',
    Claims: '声明',
    Organization: '组织',
    Organizations: '组织',
    Connector: '连接器',
    Connectors: '连接器',
    'Resource indicator': '资源指示器',
    'Resource indicators': '资源指示器',
    'Consent screen': '用户授权页面',
    'Machine-to-machine': '机器对机器',
    Experience: '体验',
    'API resource': 'API 资源',
    'API resources': 'API 资源',
    'Role-based access control': '基于角色的访问控制 (RBAC)',
    'User impersonation': '用户模拟',
    'Identity provider': '身份提供商 (IdP)',
    'Single sign-on': '单点登录 (SSO)',
    'Enterprise SSO': '企业单点登录 (SSO)',
    'Multi-factor authentication': '多因素认证 (MFA)',
    'Authentication request': '认证请求',
    'Authorization request': '授权请求',
    'Token request': '令牌请求',
    'Authorization token': '授权令牌',
  },
  fr: {
    Authentication: 'Authentification',
    Authorization: 'Autorisation',
    'Opaque token': 'Jeton opaque',
    'Opaque tokens': 'Jetons opaques',
    'Access token': 'Jeton d’accès',
    'Access tokens': 'Jetons d’accès',
    'Refresh token': 'Jeton de rafraîchissement',
    'Refresh tokens': 'Jetons de rafraîchissement',
    'Organization token': 'Jeton d’organisation',
    'Organization tokens': 'Jetons d’organisation',
    'ID token': 'Jeton d’identifiant',
    'ID tokens': 'Jetons d’identifiant',
    Issuer: 'Émetteur',
    Issuers: 'Émetteurs',
    Role: 'Rôle',
    Roles: 'Rôles',
    Audience: 'Audience',
    Audiences: 'Audiences',
    Subject: 'Sujet',
    Subjects: 'Sujets',
    Scope: 'Portée',
    Scopes: 'Portées',
    Permission: 'Permission',
    Permissions: 'Permissions',
    Claim: 'Revendication',
    Claims: 'Revendications',
    Organization: 'Organisation',
    Organizations: 'Organisations',
    Connector: 'Connecteur',
    Connectors: 'Connecteurs',
    'Resource indicator': 'Indicateur de ressource',
    'Resource indicators': 'Indicateurs de ressource',
    'Consent screen': 'Écran de consentement',
    'Machine-to-machine': 'Machine à machine',
    Experience: 'Expérience',
    'API resource': 'Ressource API',
    'API resources': 'Ressources API',
    'Role-based access control': 'Contrôle d’accès basé sur les rôles (RBAC)',
    'User impersonation': 'Usurpation d’identité utilisateur',
    'Identity provider': 'Fournisseur d’identité (IdP)',
    'Single sign-on': 'Authentification unique (SSO)',
    'Enterprise SSO': 'SSO d’entreprise',
    'Multi-factor authentication': 'Authentification multi-facteurs (MFA)',
    'Authentication request': 'Requête d’authentification',
    'Authorization request': 'Requête d’autorisation',
    'Token request': 'Requête de jeton',
    'Authorization token': 'Jeton d’autorisation',
  },
  de: {
    Authentication: 'Authentifizierung',
    Authorization: 'Autorisierung',
    'Opaque token': 'Opaker Token',
    'Opaque tokens': 'Opake Tokens',
    'Access token': 'Zugangstoken',
    'Access tokens': 'Zugangstokens',
    'Refresh token': 'Auffrischungstoken',
    'Refresh tokens': 'Auffrischungstokens',
    'Organization token': 'Organisationstoken',
    'Organization tokens': 'Organisationstokens',
    'ID token': 'ID-Token',
    'ID tokens': 'ID-Tokens',
    Issuer: 'Aussteller',
    Issuers: 'Aussteller',
    Role: 'Rolle',
    Roles: 'Rollen',
    Audience: 'Zielgruppe',
    Audiences: 'Zielgruppen',
    Subject: 'Subjekt',
    Subjects: 'Subjekte',
    Scope: 'Berechtigung',
    Scopes: 'Berechtigungen',
    Permission: 'Berechtigung',
    Permissions: 'Berechtigungen',
    Claim: 'Anspruch',
    Claims: 'Ansprüche',
    Organization: 'Organisation',
    Organizations: 'Organisationen',
    Connector: 'Connector',
    Connectors: 'Connectors',
    'Resource indicator': 'Ressourcenindikator',
    'Resource indicators': 'Ressourcenindikatoren',
    'Consent screen': 'Zustimmungsbildschirm',
    'Machine-to-machine': 'Maschine-zu-Maschine',
    Experience: 'Erfahrung',
    'API resource': 'API-Ressource',
    'API resources': 'API-Ressourcen',
    'Role-based access control': 'Rollenbasierte Zugangskontrolle (RBAC)',
    'User impersonation': 'Benutzermimikry',
    'Identity provider': 'Identitätsanbieter (IdP)',
    'Multi-factor authentication': 'Multi-Faktor-Authentifizierung (MFA)',
    'Authentication request': 'Authentifizierungsanfrage',
    'Authorization request': 'Autorisierungsanfrage',
    'Token request': 'Token-Anfrage',
    'Authorization token': 'Autorisierungstoken',
  },
  es: {
    Authentication: 'Autenticación',
    Authorization: 'Autorización',
    'Opaque token': 'Token opaco',
    'Opaque tokens': 'Tokens opacos',
    'Access token': 'Token de acceso',
    'Access tokens': 'Tokens de acceso',
    'Refresh token': 'Token de actualización',
    'Refresh tokens': 'Tokens de actualización',
    'Organization token': 'Token de organización',
    'Organization tokens': 'Tokens de organización',
    'ID token': 'Token de ID',
    'ID tokens': 'Tokens de ID',
    Issuer: 'Emisor',
    Issuers: 'Emisores',
    Role: 'Rol',
    Roles: 'Roles',
    Audience: 'Audiencia',
    Audiences: 'Audiencias',
    Subject: 'Sujeto',
    Subjects: 'Sujetos',
    Scope: 'Alcance',
    Scopes: 'Alcances',
    Permission: 'Permiso',
    Permissions: 'Permisos',
    Claim: 'Reclamo',
    Claims: 'Reclamos',
    Organization: 'Organización',
    Organizations: 'Organizaciones',
    Connector: 'Conector',
    Connectors: 'Conectores',
    'Resource indicator': 'Indicador de recurso',
    'Resource indicators': 'Indicadores de recurso',
    'Consent screen': 'Pantalla de consentimiento',
    'Machine-to-machine': 'Máquina a máquina',
    Experience: 'Experiencia',
    'API resource': 'Recurso de API',
    'API resources': 'Recursos de API',
    'Role-based access control': 'Control de acceso basado en roles (RBAC)',
    'User impersonation': 'Suplantación de usuario',
    'Identity provider': 'Proveedor de identidad (IdP)',
    'Single sign-on': 'Inicio de sesión único (SSO)',
    'Enterprise SSO': 'SSO empresarial',
    'Multi-factor authentication': 'Autenticación multifactor (MFA)',
    'Authentication request': 'Solicitud de autenticación',
    'Authorization request': 'Solicitud de autorización',
    'Token request': 'Solicitud de token',
    'Authorization token': 'Token de autorización',
  },
  'pt-BR': {
    Authentication: 'Autenticação',
    Authorization: 'Autorização',
    'Opaque token': 'Token opaco',
    'Opaque tokens': 'Tokens opacos',
    'Access token': 'Token de acesso',
    'Access tokens': 'Tokens de acesso',
    'Refresh token': 'Token de atualização',
    'Refresh tokens': 'Tokens de atualização',
    'Organization token': 'Token de organização',
    'Organization tokens': 'Tokens de organização',
    'ID token': 'Token de ID',
    'ID tokens': 'Tokens de ID',
    Issuer: 'Emissor',
    Issuers: 'Emissores',
    Role: 'Papel',
    Roles: 'Papéis',
    Audience: 'Público',
    Audiences: 'Públicos',
    Subject: 'Sujeito',
    Subjects: 'Sujeitos',
    Scope: 'Escopo',
    Scopes: 'Escopos',
    Permission: 'Permissão',
    Permissions: 'Permissões',
    Claim: 'Reivindicação',
    Claims: 'Reivindicações',
    Organization: 'Organização',
    Organizations: 'Organizações',
    Connector: 'Conector',
    Connectors: 'Conectores',
    'Resource indicator': 'Indicador de recurso',
    'Resource indicators': 'Indicadores de recurso',
    'Consent screen': 'Tela de consentimento',
    'Machine-to-machine': 'Máquina para máquina',
    Experience: 'Experiência',
    'API resource': 'Recurso de API',
    'API resources': 'Recursos de API',
    'Role-based access control': 'Controle de acesso baseado em papel (RBAC)',
    'User impersonation': 'Imitação de usuário',
    'Identity provider': 'Provedor de identidade (IdP)',
    'Single sign-on': 'Autenticação única (SSO)',
    'Enterprise SSO': 'SSO corporativo (SSO)',
    'Multi-factor authentication': 'Autenticação multifatorial (MFA)',
    'Authentication request': 'Solicitação de autenticação',
    'Authorization request': 'Solicitação de autorização',
    'Token request': 'Solicitação de token',
    'Authorization token': 'Token de autorização',
  },
  ja: {
    Authentication: '認証',
    Authorization: '認可',
    'Opaque token': '不透明トークン',
    'Opaque tokens': '不透明トークン',
    'Access token': 'アクセス トークン',
    'Access tokens': 'アクセス トークン',
    'Refresh token': 'リフレッシュ トークン',
    'Refresh tokens': 'リフレッシュ トークン',
    'Organization token': '組織トークン',
    'Organization tokens': '組織トークン',
    'ID token': 'ID トークン',
    'ID tokens': 'ID トークン',
    Issuer: '発行者',
    Issuers: '発行者',
    Role: 'ロール',
    Roles: 'ロール',
    Audience: 'オーディエンス',
    Audiences: 'オーディエンス',
    Subject: 'サブジェクト',
    Subjects: 'サブジェクト',
    Scope: 'スコープ',
    Scopes: 'スコープ',
    Permission: '権限',
    Permissions: '権限',
    Claim: 'クレーム',
    Claims: 'クレーム',
    Organization: '組織',
    Organizations: '組織',
    Connector: 'コネクター',
    Connectors: 'コネクター',
    'Resource indicator': 'リソースインジケーター',
    'Resource indicators': 'リソースインジケーター',
    'Consent screen': '同意画面',
    'Machine-to-machine': 'マシン間通信',
    Experience: '体験',
    'API resource': 'API リソース',
    'API resources': 'API リソース',
    'Role-based access control': 'ロールベースのアクセス制御 (RBAC)',
    'User impersonation': 'ユーザーなりすまし',
    'Identity provider': 'アイデンティティプロバイダー (IdP)',
    'Single sign-on': 'シングルサインオン (SSO)',
    'Enterprise SSO': 'エンタープライズシングルサインオン (SSO)',
    'Multi-factor authentication': '多要素認証 (MFA)',
    'Authentication request': '認証リクエスト',
    'Authorization request': '認可リクエスト',
    'Token request': 'トークンリクエスト',
    'Authorization token': '認可トークン',
  },
  ko: {
    Authentication: '인증',
    Authorization: '인가',
    'Opaque token': '불투명 토큰',
    'Opaque tokens': '불투명 토큰',
    'Access token': '액세스 토큰',
    'Access tokens': '액세스 토큰',
    'Refresh token': '리프레시 토큰',
    'Refresh tokens': '리프레시 토큰',
    'Organization token': '조직 토큰',
    'Organization tokens': '조직 토큰',
    'ID token': 'ID 토큰',
    'ID tokens': 'ID 토큰',
    Issuer: '발급자',
    Issuers: '발급자',
    Role: '역할',
    Roles: '역할',
    Audience: '대상',
    Audiences: '대상',
    Subject: '주체',
    Subjects: '주체',
    Scope: '스코프',
    Scopes: '스코프',
    Permission: '권한',
    Permissions: '권한',
    Claim: '클레임',
    Claims: '클레임',
    Organization: '조직',
    Organizations: '조직',
    Connector: '커넥터',
    Connectors: '커넥터',
    'Resource indicator': '리소스 지표',
    'Resource indicators': '리소스 지표',
    'Consent screen': '동의 화면',
    'Machine-to-machine': '기계 간',
    Experience: '경험',
    'API resource': 'API 리소스',
    'API resources': 'API 리소스',
    'Role-based access control': '역할 기반 접근 제어 (RBAC)',
    'User impersonation': '사용자 가장',
    'Identity provider': '아이덴티티 제공자 (IdP)',
    'Single sign-on': '싱글 사인온 (SSO)',
    'Enterprise SSO': '엔터프라이즈 싱글 사인온 (SSO)',
    'Multi-factor authentication': '다단계 인증 (MFA)',
    'Authentication request': '인증 요청',
    'Authorization request': '인가 요청',
    'Token request': '토큰 요청',
    'Authorization token': '인가 토큰',
  },
});

export const patterns = Object.freeze({
  'zh-CN': {
    'Set up social login with {provider}': '设置 {provider} 社交登录',
    'Add authentication to your {framework} application':
      '为你的 {framework} 应用添加认证 (Authentication)',
    'Set up email verification with {provider}': '使用 {provider} 设置电子邮件验证',
    'Set up SMS verification with {provider}': '使用 {provider} 设置短信验证',
    'Set up Single Sign-On with {provider}': '设置 {provider} 单点登录',
  },
  fr: {
    'Set up social login with {provider}': 'Configurer la connexion sociale avec {provider}',
    'Add authentication to your {framework} application':
      'Ajoutez l’authentification à votre application {framework}',
    'Set up email verification with {provider}':
      'Configurer la vérification par e-mail avec {provider}',
    'Set up SMS verification with {provider}': 'Configurer la vérification par SMS avec {provider}',
    'Set up Single Sign-On with {provider}': 'Configurer l’authentification unique avec {provider}',
  },
  de: {
    'Set up social login with {provider}': 'Soziale Anmeldung mit {provider} einrichten',
    'Add authentication to your {framework} application':
      'Authentifizierung zu deiner {framework}-Anwendung hinzufügen',
    'Set up email verification with {provider}': 'E-Mail-Verifizierung mit {provider} einrichten',
    'Set up SMS verification with {provider}': 'SMS-Verifizierung mit {provider} einrichten',
    'Set up Single Sign-On with {provider}': 'Single Sign-On mit {provider} einrichten',
  },
  es: {
    'Set up social login with {provider}': 'Configura el inicio de sesión social con {provider}',
    'Add authentication to your {framework} application':
      'Añade autenticación a tu aplicación {framework}',
    'Set up email verification with {provider}':
      'Configura la verificación por correo electrónico con {provider}',
    'Set up SMS verification with {provider}': 'Configura la verificación por SMS con {provider}',
    'Set up Single Sign-On with {provider}': 'Configura el inicio de sesión único con {provider}',
  },
  'pt-BR': {
    'Set up social login with {provider}': 'Configurar login social com {provider}',
    'Add authentication to your {framework} application':
      'Adicionar autenticação ao seu aplicativo {framework}',
    'Set up email verification with {provider}': 'Configurar verificação de email com {provider}',
    'Set up SMS verification with {provider}': 'Configurar verificação SMS com {provider}',
    'Set up Single Sign-On with {provider}': 'Configurar Single Sign-On com {provider}',
  },
  ja: {
    'Set up social login with {provider}': '{provider} を使用してソーシャルログインを設定する',
    'Add authentication to your {framework} application':
      'あなたの {framework} アプリケーションに認証 (Authentication) を追加する',
    'Set up email verification with {provider}': '{provider} を使用してメール認証を設定する',
    'Set up SMS verification with {provider}': '{provider} を使用してSMS認証を設定する',
    'Set up Single Sign-On with {provider}': '{provider} を使用してシングルサインオンを設定する',
  },
  ko: {
    'Set up social login with {provider}': '{provider} 소셜 로그인을 설정하세요',
    'Add authentication to your {framework} application':
      '{framework} 애플리케이션에 인증 (Authentication)을 추가하세요',
    'Set up email verification with {provider}': '{provider}로 이메일 인증을 설정하세요',
    'Set up SMS verification with {provider}': '{provider}로 SMS 인증을 설정하세요',
    'Set up Single Sign-On with {provider}': '{provider}로 싱글 사인온 (SSO)을 설정하세요',
  },
});
/* eslint-enable max-lines */
