import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import docsSidebar from './docs';
import integrationsSidebar from './integrations';
import quickStartSidebar from './quick-start';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar,
  quickStartSidebar,
  integrationsSidebar,
  apiProtectionSidebar: [{ type: 'autogenerated', dirName: 'api-protection' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

export default sidebars;
