"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var docs_1 = require("./docs");
var integrations_1 = require("./integrations");
var quick_start_1 = require("./quick-start");
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
var sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docsSidebar: docs_1.default,
    quickStartSidebar: quick_start_1.default,
    integrationsSidebar: integrations_1.default,
    useCasesSidebar: [{ type: 'autogenerated', dirName: 'use-cases' }],
    apiProtectionSidebar: [{ type: 'autogenerated', dirName: 'api-protection' }],
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
};
exports.default = sidebars;
