import type { SidebarConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

const integrations: SidebarConfig = [
  'integrations/README',
  {
    type: 'link',
    label: 'Social connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/social' },
  {
    type: 'link',
    label: 'Email connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/email' },
  {
    type: 'link',
    label: 'SMS connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/sms' },
  {
    type: 'link',
    label: 'Enterprise connectors',
    /**
     * The "additionalLabel" prop is used in "Gallery" component where the sidebar config is used
     * to generate the gallery items. The additional label is appended to the label, in order to
     * provide additional information about the category.
     */
    customProps: { additionalLabel: '(SP-initiated SSO)' },
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/sso' },
  {
    type: 'link',
    label: 'Authorization',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/authorization' },
];

export default integrations;
