import type { SidebarConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

const integrations: SidebarConfig = [
  'integrations/README',
  {
    type: 'link',
    label: 'Social connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/social' },
  {
    type: 'link',
    label: 'Email connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/email' },
  {
    type: 'link',
    label: 'SMS connectors',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/sms' },
  {
    type: 'link',
    label: 'Enterprise connectors',
    customProps: { additionalLabel: '(SP-initiated SSO)' },
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/sso' },
  {
    type: 'link',
    label: 'Third-party apps',
    customProps: { additionalLabel: '(Logto as Idp)' },
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'integrations/third-party' },
];

export default integrations;
