"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var integrations = [
    'integrations/README',
    {
        type: 'link',
        label: 'Social connectors',
        href: '#',
        className: 'sidebar-section',
    },
    { type: 'autogenerated', dirName: 'integrations/social' },
    {
        type: 'link',
        label: 'Email connectors',
        href: '#',
        className: 'sidebar-section',
    },
    { type: 'autogenerated', dirName: 'integrations/email' },
    {
        type: 'link',
        label: 'SMS connectors',
        href: '#',
        className: 'sidebar-section',
    },
    { type: 'autogenerated', dirName: 'integrations/sms' },
    {
        type: 'link',
        label: 'Enterprise connectors',
        customProps: { additionalLabel: '(SP-initiated SSO)' },
        href: '#',
        className: 'sidebar-section',
    },
    { type: 'autogenerated', dirName: 'integrations/sso' },
];
exports.default = integrations;
