import type { SidebarConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

const quickStartSidebar: SidebarConfig = [
  'quick-starts/README',
  {
    type: 'link',
    label: 'User authentication',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/framework' },
  {
    type: 'link',
    label: 'Generic',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/generic' },
  {
    type: 'link',
    label: 'Database',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/database' },
  {
    type: 'link',
    label: 'Third-party apps',
    /**
     * The "additionalLabel" prop is used in "Gallery" component where the sidebar config is used
     * to generate the gallery items. The additional label is appended to the label, in order to
     * provide additional information about the category.
     */
    customProps: { additionalLabel: '(Logto as Idp)' },
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/third-party' },
];

export default quickStartSidebar;
