import type { SidebarConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

const quickStartSidebar: SidebarConfig = [
  'quick-starts/README',
  {
    type: 'link',
    label: 'Language framework',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/framework' },
  {
    type: 'link',
    label: 'No framework and generic',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/generic' },
  {
    type: 'link',
    label: 'Database',
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/database' },
  {
    type: 'link',
    label: 'Third-party apps',
    customProps: { additionalLabel: '(Logto as Idp)' },
    href: '#',
    className: 'sidebar-section',
  },
  { type: 'autogenerated', dirName: 'quick-starts/third-party' },
];

export default quickStartSidebar;
